#include "pomp_lib.h"

struct ompregdescr omp_rd_45 = {
  "parallelfor", "", 0, "lbp_omp.c", 109, 109, 111, 111
};

#define POMP_DLIST_00045 shared(omp_rd_45)

struct ompregdescr omp_rd_46 = {
  "parallelfor", "", 0, "lbp_omp.c", 142, 142, 146, 146
};

#define POMP_DLIST_00046 shared(omp_rd_46)

struct ompregdescr omp_rd_47 = {
  "parallelfor", "", 0, "lbp_omp.c", 148, 148, 152, 152
};

#define POMP_DLIST_00047 shared(omp_rd_47)

struct ompregdescr omp_rd_48 = {
  "parallelfor", "", 0, "lbp_omp.c", 156, 156, 165, 165
};

#define POMP_DLIST_00048 shared(omp_rd_48)

struct ompregdescr omp_rd_49 = {
  "parallelfor", "", 0, "lbp_omp.c", 179, 179, 183, 183
};

#define POMP_DLIST_00049 shared(omp_rd_49)

struct ompregdescr omp_rd_50 = {
  "parallelfor", "", 0, "lbp_omp.c", 190, 190, 192, 192
};

#define POMP_DLIST_00050 shared(omp_rd_50)

struct ompregdescr omp_rd_51 = {
  "parallelfor", "", 0, "lbp_omp.c", 194, 194, 197, 197
};

#define POMP_DLIST_00051 shared(omp_rd_51)

